// AUTO-GENERATED by scripts/gen-schema.mjs from schemas/real_estate.schema.json.
// Do not edit by hand: run `npm run gen:schema` after the agent's schema changes.
/* eslint-disable */
import { z } from 'zod';
import { bestUnion, optionalField, seriesNumber, tolerantArray, tolerantRecord } from './tolerant';

export const AffordabilityOutSchema = z.object({
  assumptions: z.record(z.string(), z.number().nullable()),
  income_year: optionalField(z.number().nullable(), null, "AffordabilityOut.income_year"),
  median_household_income: optionalField(z.number().nullable(), null, "AffordabilityOut.median_household_income"),
  payment_change_pct: optionalField(z.number().nullable(), null, "AffordabilityOut.payment_change_pct"),
  payment_now: z.number(),
  payment_to_income: optionalField(z.number().nullable(), null, "AffordabilityOut.payment_to_income"),
  payment_year_ago: optionalField(z.number().nullable(), null, "AffordabilityOut.payment_year_ago"),
});
export type AffordabilityOut = z.output<typeof AffordabilityOutSchema>;

/** One metro in an alert group, with its own figure (the group label is a threshold). */
export const AlertMetroSchema = z.object({
  label: z.string(),
  name: z.string(),
  severity: z.enum(["info", "notable", "major"]),
  slug: z.string(),
  value: optionalField(z.number().nullable(), null, "AlertMetro.value"),
});
export type AlertMetro = z.output<typeof AlertMetroSchema>;

export const AlertOutSchema = z.object({
  flag: z.string(),
  label: z.string(),
  metros: optionalField(tolerantArray(AlertMetroSchema, "AlertOut.metros"), [], "AlertOut.metros"),
  severity: z.enum(["info", "notable", "major"]),
  slugs: z.array(z.string()),
});
export type AlertOut = z.output<typeof AlertOutSchema>;

/** A source attribution on a brief or in `sources` (§6.1). Deliberately not agents-core's `Citation` (source/url/note): §6's shape is name/url/attribution. */
export const CitationSchema = z.object({
  attribution: optionalField(z.string().nullable(), null, "Citation.attribution"),
  name: z.string(),
  url: z.string(),
});
export type Citation = z.output<typeof CitationSchema>;

export const BriefSchema = z.object({
  citations: optionalField(tolerantArray(CitationSchema, "Brief.citations"), [], "Brief.citations"),
  generated_at: z.string(),
  key_points: optionalField(z.array(z.string()), [], "Brief.key_points"),
  model: optionalField(z.string().nullable(), null, "Brief.model"),
  narrative_source: z.enum(["llm", "template"]),
  reused: optionalField(z.boolean(), false, "Brief.reused"),
  text: z.string(),
});
export type Brief = z.output<typeof BriefSchema>;

export const CaseShillerSchema = z.object({
  period: optionalField(z.string().nullable(), null, "CaseShiller.period"),
  value: z.number().nullable(),
  yoy: optionalField(z.number().nullable(), null, "CaseShiller.yoy"),
});
export type CaseShiller = z.output<typeof CaseShillerSchema>;

export const ConstructionSeriesValueSchema = z.object({
  mom: optionalField(z.number().nullable(), null, "ConstructionSeriesValue.mom"),
  period: optionalField(z.string().nullable(), null, "ConstructionSeriesValue.period"),
  units: optionalField(z.string().nullable(), null, "ConstructionSeriesValue.units"),
  value: z.number().nullable(),
});
export type ConstructionSeriesValue = z.output<typeof ConstructionSeriesValueSchema>;

export const FlagOutSchema = z.object({
  facts: optionalField(z.record(z.string(), z.number()), {}, "FlagOut.facts"),
  id: z.string(),
  label: z.string(),
  severity: z.enum(["info", "notable", "major"]),
});
export type FlagOut = z.output<typeof FlagOutSchema>;

/** §6.3: one entry of the index-level `investigations` list. */
export const InvestigationSummarySchema = z.object({
  cited_metrics: z.array(z.string()),
  name: z.string(),
  narrative_source: z.enum(["llm", "template"]),
  slug: z.string(),
  stop_reason: z.string(),
  summary: z.string(),
  trigger: z.enum(["new_major_flag", "top_mover"]),
  trigger_label: z.string(),
});
export type InvestigationSummary = z.output<typeof InvestigationSummarySchema>;

export const KeyStatSchema = z.object({
  delta: optionalField(z.number().nullable(), null, "KeyStat.delta"),
  delta_format: optionalField(z.enum(["currency_compact", "currency", "percent", "percent_signed", "pp_signed", "count", "count_signed", "count_signed_thousands", "decimal1", "days", "ratio"]).nullable(), null, "KeyStat.delta_format"),
  format: z.enum(["currency_compact", "currency", "percent", "percent_signed", "pp_signed", "count", "count_signed", "count_signed_thousands", "decimal1", "days", "ratio"]),
  good_direction: optionalField(z.enum(["up", "down", "neutral"]), "neutral", "KeyStat.good_direction"),
  label: z.string(),
  value: z.number().nullable(),
});
export type KeyStat = z.output<typeof KeyStatSchema>;

export const MetricRegistryEntrySchema = z.object({
  change_kind: z.enum(["ratio", "pp", "diff"]),
  format: z.string(),
  good_direction: z.enum(["up", "down", "neutral"]),
  key: z.string(),
  label: z.string(),
  note: optionalField(z.string().nullable(), null, "MetricRegistryEntry.note"),
  source: z.string(),
});
export type MetricRegistryEntry = z.output<typeof MetricRegistryEntrySchema>;

/** `metros[].latest.<metric>` in the index (§6.1): just `value` and `yoy`. The full `MetricValue` (mom, delta_format, ranks, ...) is in `metros/<slug>.json`. */
export const MetricSummaryValueSchema = z.object({
  value: z.number().nullable(),
  yoy: optionalField(z.number().nullable(), null, "MetricSummaryValue.yoy"),
});
export type MetricSummaryValue = z.output<typeof MetricSummaryValueSchema>;

/** Permits use a rolling-12-month YoY instead of yoy/mom/trend (§5.1). */
export const PermitsValueSchema = z.object({
  value: z.number().nullable(),
  yoy_12m: optionalField(z.number().nullable(), null, "PermitsValue.yoy_12m"),
});
export type PermitsValue = z.output<typeof PermitsValueSchema>;

export const TemperatureSummarySchema = z.object({
  basis: optionalField(z.string().nullable(), null, "TemperatureSummary.basis"),
  label: z.string().nullable(),
  score: z.number().nullable(),
});
export type TemperatureSummary = z.output<typeof TemperatureSummarySchema>;

export const MetroSummarySchema = z.object({
  brief_excerpt: optionalField(z.string(), "", "MetroSummary.brief_excerpt"),
  cbsa: z.string().nullable(),
  flags: optionalField(z.array(z.string()), [], "MetroSummary.flags"),
  homes_sold_12m: optionalField(z.number().nullable(), null, "MetroSummary.homes_sold_12m"),
  lat: z.number().nullable(),
  latest: tolerantRecord(bestUnion([MetricSummaryValueSchema, PermitsValueSchema] as const), "MetroSummary.latest"),
  lon: z.number().nullable(),
  market_type: z.string().nullable(),
  name: z.string(),
  slug: z.string(),
  spark: optionalField(z.array(seriesNumber), [], "MetroSummary.spark"),
  stale: optionalField(z.boolean(), false, "MetroSummary.stale"),
  temperature: TemperatureSummarySchema,
});
export type MetroSummary = z.output<typeof MetroSummarySchema>;

export const MoverEntrySchema = z.object({
  name: z.string(),
  slug: z.string(),
  value: z.number(),
});
export type MoverEntry = z.output<typeof MoverEntrySchema>;

export const MoversSchema = z.object({
  inventory_growth: optionalField(tolerantArray(MoverEntrySchema, "Movers.inventory_growth"), [], "Movers.inventory_growth"),
  price_declines: optionalField(tolerantArray(MoverEntrySchema, "Movers.price_declines"), [], "Movers.price_declines"),
  price_gains: optionalField(tolerantArray(MoverEntrySchema, "Movers.price_gains"), [], "Movers.price_gains"),
  temperature_bottom: optionalField(tolerantArray(MoverEntrySchema, "Movers.temperature_bottom"), [], "Movers.temperature_bottom"),
  temperature_top: optionalField(tolerantArray(MoverEntrySchema, "Movers.temperature_top"), [], "Movers.temperature_top"),
});
export type Movers = z.output<typeof MoversSchema>;

export const MetricValueSchema = z.object({
  delta_format: optionalField(z.enum(["currency_compact", "currency", "percent", "percent_signed", "pp_signed", "count", "count_signed", "count_signed_thousands", "decimal1", "days", "ratio"]).nullable(), null, "MetricValue.delta_format"),
  high_36m: optionalField(z.boolean().nullable(), null, "MetricValue.high_36m"),
  low_36m: optionalField(z.boolean().nullable(), null, "MetricValue.low_36m"),
  mom: optionalField(z.number().nullable(), null, "MetricValue.mom"),
  pct_rank: optionalField(z.number().nullable(), null, "MetricValue.pct_rank"),
  trend_3m: optionalField(z.enum(["up", "down", "flat"]).nullable(), null, "MetricValue.trend_3m"),
  value: z.number().nullable(),
  yoy: optionalField(z.number().nullable(), null, "MetricValue.yoy"),
  yoy_pct_rank: optionalField(z.number().nullable(), null, "MetricValue.yoy_pct_rank"),
});
export type MetricValue = z.output<typeof MetricValueSchema>;

export const NationalConstructionSchema = z.object({
  housing_starts: ConstructionSeriesValueSchema,
  permits: ConstructionSeriesValueSchema,
  series: z.record(z.string(), z.union([z.array(z.string()), z.array(seriesNumber)])),
});
export type NationalConstruction = z.output<typeof NationalConstructionSchema>;

export const RatesLatestSchema = z.object({
  mortgage30: optionalField(z.number().nullable(), null, "RatesLatest.mortgage30"),
  mortgage30_change_1w_pp: optionalField(z.number().nullable(), null, "RatesLatest.mortgage30_change_1w_pp"),
  mortgage30_year_ago: optionalField(z.number().nullable(), null, "RatesLatest.mortgage30_year_ago"),
});
export type RatesLatest = z.output<typeof RatesLatestSchema>;

export const NationalRatesSchema = z.object({
  dates: z.array(z.string()),
  latest: RatesLatestSchema,
  mortgage15: z.array(seriesNumber),
  mortgage30: z.array(seriesNumber),
});
export type NationalRates = z.output<typeof NationalRatesSchema>;

export const NationalBlockSchema = z.object({
  brief: BriefSchema,
  case_shiller: optionalField(CaseShillerSchema.nullable(), null, "NationalBlock.case_shiller"),
  construction: NationalConstructionSchema,
  latest: tolerantRecord(MetricValueSchema, "NationalBlock.latest"),
  rates: NationalRatesSchema,
  series: z.record(z.string(), z.union([z.array(z.string()), z.array(seriesNumber)])),
  temperature: TemperatureSummarySchema,
});
export type NationalBlock = z.output<typeof NationalBlockSchema>;

export const TierUsageSchema = z.object({
  input_tokens: optionalField(z.number(), 0, "TierUsage.input_tokens"),
  output_tokens: optionalField(z.number(), 0, "TierUsage.output_tokens"),
});
export type TierUsage = z.output<typeof TierUsageSchema>;

export const ModelUsageSchema = z.object({
  fast: optionalField(TierUsageSchema, undefined, "ModelUsage.fast"),
  smart: optionalField(TierUsageSchema, undefined, "ModelUsage.smart"),
});
export type ModelUsage = z.output<typeof ModelUsageSchema>;

/** A dataset or page an agent pulled from, shown in the site's source list. */
export const SourceSchema = z.object({
  name: z.string(),
  retrieved_at: z.string(),
  url: z.string(),
});
export type Source = z.output<typeof SourceSchema>;

/** The `meta` block at the top of every agent's `latest.json`. Agent-specific meta fields: subclass `RunMeta` (fields need defaults), declare `meta: MyMeta` on your `AgentOutput` subclass, and return the values in `AgentResult.meta_fields`. The runner merges them into `meta` before validating, so they're published in latest.json and appear in schema.json. */
export const RunMetaSchema = z.object({
  agent: z.string(),
  cost_usd: z.number(),
  data_changed: z.boolean(),
  finished_at: z.string(),
  meta_schema_version: optionalField(z.string(), "1.1.0", "RunMeta.meta_schema_version"),
  model_usage: ModelUsageSchema,
  run_id: z.string(),
  schema_version: z.string(),
  sources: tolerantArray(SourceSchema, "RunMeta.sources"),
  started_at: z.string(),
  status: z.enum(["ok", "stale", "failed"]),
  warnings: optionalField(z.array(z.string()), [], "RunMeta.warnings"),
});
export type RunMeta = z.output<typeof RunMetaSchema>;

export const IndexOutputSchema = z.object({
  alerts: tolerantArray(AlertOutSchema, "IndexOutput.alerts"),
  data_through: z.string(),
  headline: z.string(),
  investigations: optionalField(tolerantArray(InvestigationSummarySchema, "IndexOutput.investigations"), [], "IndexOutput.investigations"),
  key_stats: tolerantArray(KeyStatSchema, "IndexOutput.key_stats"),
  meta: RunMetaSchema,
  metric_registry: tolerantArray(MetricRegistryEntrySchema, "IndexOutput.metric_registry"),
  metros: tolerantArray(MetroSummarySchema, "IndexOutput.metros"),
  movers: MoversSchema,
  national: NationalBlockSchema,
  rates_as_of: z.string(),
  sources: tolerantArray(CitationSchema, "IndexOutput.sources"),
});
export type IndexOutput = z.output<typeof IndexOutputSchema>;

/** §6.3: the metro investigator's "why this is happening" explanation (`metros/<slug>.json` → `investigation`). Additive: null for metros not investigated this run. */
export const InvestigationSchema = z.object({
  cited_metrics: z.array(z.string()),
  cost_usd: z.number(),
  explanation: z.string(),
  generated_at: z.string(),
  model: optionalField(z.string().nullable(), null, "Investigation.model"),
  name: z.string(),
  narrative_source: z.enum(["llm", "template"]),
  prompt_version: z.string(),
  reused: optionalField(z.boolean(), false, "Investigation.reused"),
  slug: z.string(),
  steps: z.number(),
  stop_reason: z.string(),
  tools_called: optionalField(z.array(z.string()), [], "Investigation.tools_called"),
  trigger: z.enum(["new_major_flag", "top_mover"]),
  trigger_flag: optionalField(z.string().nullable(), null, "Investigation.trigger_flag"),
  trigger_label: z.string(),
});
export type Investigation = z.output<typeof InvestigationSchema>;

export const TemperatureDetailSchema = z.object({
  components: optionalField(z.record(z.string(), z.number()), {}, "TemperatureDetail.components"),
  label: z.string().nullable(),
  score: z.number().nullable(),
});
export type TemperatureDetail = z.output<typeof TemperatureDetailSchema>;

export const MetroDetailOutputSchema = z.object({
  affordability: AffordabilityOutSchema.nullable(),
  brief: BriefSchema,
  cbsa: z.string().nullable(),
  data_through: z.string(),
  flags: tolerantArray(FlagOutSchema, "MetroDetailOutput.flags"),
  investigation: optionalField(InvestigationSchema.nullable(), null, "MetroDetailOutput.investigation"),
  lat: z.number().nullable(),
  latest: tolerantRecord(bestUnion([MetricValueSchema, PermitsValueSchema] as const), "MetroDetailOutput.latest"),
  lon: z.number().nullable(),
  market_type: z.string().nullable(),
  name: z.string(),
  series: z.record(z.string(), z.union([z.array(z.string()), z.array(seriesNumber)])),
  slug: z.string(),
  stale: optionalField(z.boolean(), false, "MetroDetailOutput.stale"),
  temperature: TemperatureDetailSchema,
});
export type MetroDetailOutput = z.output<typeof MetroDetailOutputSchema>;
