"""Build `config/county_centroids.csv` (§6.7): a Census Gazetteer internal point for
every county Redfin lists under a tracked metro, keyed by Redfin's county name.

Run once (and whenever `config/metros.toml` changes); the agent only reads the
committed file, so a weekly run never fetches the Gazetteer. Matching is by
"<Gazetteer NAME>, <USPS>" (Redfin's "Bergen County, NJ"). The 2024 file comes first;
the 2020 file fills counties that no longer exist in 2024 (Connecticut's former
counties, which Redfin still reports), and independent cities are matched by their
Gazetteer spelling ("Alexandria, VA" -> "Alexandria city"). Anything still unmatched is printed and left
out: the site skips an area without a centroid.

    uv run python scripts/build_county_centroids.py
"""

from __future__ import annotations

import csv
import io
import zipfile
from pathlib import Path

import polars as pl
from agents_core.http import Http

from agents.real_estate import fetch_redfin
from agents.real_estate.areas import AREA_COLUMNS, DEFAULT_CENTROIDS_PATH
from agents.real_estate.config import load_metros

GAZETTEER = [
    "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2024_Gazetteer/2024_Gaz_counties_national.zip",
    "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2020_Gazetteer/2020_Gaz_counties_national.zip",
]


def parse_gazetteer(raw: bytes) -> dict[str, tuple[str, float, float]]:
    with zipfile.ZipFile(io.BytesIO(raw)) as zf:
        name = next(n for n in zf.namelist() if n.endswith(".txt"))
        text = zf.read(name).decode("latin-1")
    reader = csv.DictReader(io.StringIO(text), delimiter="\t")
    out: dict[str, tuple[str, float, float]] = {}
    for row in reader:
        row = {k.strip(): (v or "").strip() for k, v in row.items() if k}
        out[f"{row['NAME']}, {row['USPS']}"] = (row["GEOID"], float(row["INTPTLAT"]), float(row["INTPTLONG"]))
    return out


def candidates(name: str) -> list[str]:
    """Redfin's name, then its independent-city spellings: Redfin writes Virginia's and
    Maryland's/Missouri's independent cities as "Alexandria, VA" and "Baltimore City
    County, MD"; the Gazetteer as "Alexandria city" and "Baltimore city"."""
    place, _, state = name.rpartition(", ")
    out = [name]
    if place.endswith(" City County"):
        out.append(f"{place.removesuffix(' City County')} city, {state}")
    elif not place.endswith((" County", " Parish", " Borough", " Planning Region")):
        out.append(f"{place} city, {state}")
    return out


def main() -> int:
    metros = load_metros()
    tracked = {m.redfin_region for m in metros}
    with Http(cache_dir=Path("data/cache/http")) as http:
        fetched = fetch_redfin.fetch_counties(http, tracked_regions=tracked, columns=AREA_COLUMNS)
        gazetteers = [parse_gazetteer(http.get(url).content) for url in GAZETTEER]
    counties = sorted(set(pl.read_parquet(fetched.parquet_path)["region"].drop_nulls().to_list()))
    rows, unmatched = [], []
    for name in counties:
        hit = next((g[c] for c in candidates(name) for g in gazetteers if c in g), None)
        if hit is None:
            unmatched.append(name)
        else:
            rows.append((name, hit[0], round(hit[1], 5), round(hit[2], 5)))
    with DEFAULT_CENTROIDS_PATH.open("w", encoding="utf8", newline="\n") as f:
        f.write("# Generated by scripts/build_county_centroids.py (Census Gazetteer internal points).\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["name", "geoid", "lat", "lon"])
        w.writerows(rows)
    print(f"{len(rows)} counties written to {DEFAULT_CENTROIDS_PATH}; {len(unmatched)} unmatched")
    for name in unmatched:
        print("  unmatched:", name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
